spring.application.name=fake-image-detector
server.port=8081


# gemini api key 
gemini.api.key=${GEMINI_API_KEY}



# Allow files up to 10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

